Repository stan-dev/math, pull requests merged in 2018-09, with the labels that each got.

#967 gpu matrix multiply
  stan/math/gpu/diagonal_multiply.hpp
  stan/math/gpu/kernel_cl.hpp
  stan/math/gpu/kernels/helpers.hpp
  stan/math/gpu/kernels/matrix_multiply.hpp
  stan/math/gpu/kernels/multiply_transpose.hpp
  stan/math/gpu/kernels/scalar_mul.hpp
  stan/math/gpu/kernels/scalar_mul_diagonal.hpp
  stan/math/gpu/multiply.hpp
  stan/math/gpu/multiply_transpose.hpp
  stan/math/gpu/opencl_context.hpp
  test/unit/math/gpu/diagonal_multiply_test.cpp
  test/unit/math/gpu/multiply_test.cpp
  test/unit/math/gpu/multiply_transpose_test.cpp
  test/unit/math/gpu/opencl_context_test.cpp
Labels: feature, gpu

#1035 Remove argument decorators from GPU kernel signatures
  stan/math/gpu/kernels/add.hpp
  stan/math/gpu/kernels/check_diagonal_zeros.hpp
  stan/math/gpu/kernels/check_nan.hpp
  stan/math/gpu/kernels/check_symmetric.hpp
  stan/math/gpu/kernels/copy.hpp
  stan/math/gpu/kernels/copy_triangular.hpp
  stan/math/gpu/kernels/identity.hpp
  stan/math/gpu/kernels/matrix_multiply.hpp
  stan/math/gpu/kernels/multiply_transpose.hpp
  stan/math/gpu/kernels/scalar_mul_diagonal.hpp
  stan/math/gpu/kernels/sub_block.hpp
  stan/math/gpu/kernels/subtract.hpp
  stan/math/gpu/kernels/transpose.hpp
  stan/math/gpu/kernels/triangular_transpose.hpp
  stan/math/gpu/kernels/zeros.hpp
Labels: windows

#1042 makefile fixes: setting DEPFLAGS_OS only if it hasn't been set by the user; adds O option to building Sundials
  make/dependencies
  make/libraries
Labels: bug, build
